from flask import Flask
from flask import render_template
import random
import csv

app = Flask(__name__)



@app.route('/gate/')
def blank(done=None):
    done=["",""]

    return render_template('gate.html', name="<BR>", done=done)


@app.route('/gate/<name>/')
def gate(name=None):
    # open file with sold tickets and create list of lines
    with open("soldTickets.csv") as file:
        soldTickets = [line.rstrip() for line in file]

    # select winner 
    winner = random.choice(soldTickets)

    # remove winner from input soldTickets 
    soldTickets.remove(winner)

    # implode list back to file with line breaks
    with open('soldTickets.csv', mode='w', encoding='utf-8') as myfile:
        myfile.write('\n'.join(soldTickets))
        # add line break to end of file 
        myfile.write('\n')


    #open winner CSV file create List
    with open("outWinners.csv") as file:
        
        outWinners = [line.rstrip() for line in file]
        
    # Yield successive n-sized chunks from l
    def divide_chunks(l, n): 
        
        # looping till length l 
        for i in range(0, len(l), n):  
            yield '<BR>'.join(l[i:i + n]) 
    
    # n = elements each list should have on page
    n = 25
    
    #list of lists generated by divide_chunks. 
    done = list(divide_chunks(outWinners, n)) 
    

    # add winner to end of file plus line break 
    with open('outWinners.csv', mode='a', encoding='utf-8') as myfile:
        myfile.write(winner)
        myfile.write('\n')



    
    return render_template('gate.html', name=winner.replace(" ","<BR>"), done=done)